###############################################################################
# .gitlab-ci.yml
# Copyright (c) 2026 Jeffrey H. Johnson
# SPDX-License-Identifier: MIT-0
# scspell-id: 03a06400-54ce-11f1-9a53-80ee73e9b8e7
###############################################################################

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 0

###############################################################################

before_script:
  - apk update || true
  - apk add git
  - git fetch origin
  - git checkout -B "$CI_COMMIT_REF_NAME" "origin/$CI_COMMIT_REF_NAME"

###############################################################################

pages:
  stage: deploy
  image: alpine:edge
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - export TZ=UTC
    - apk update || true
    - apk add '!usr-merge-nag' 2> /dev/null || true
    - apk upgrade --prune || true
    - apk add make gcc libc-dev upx dev86
    - ( cd /tmp && git clone https://github.com/dmsc/emu2.git && cd emu2 && make && make install && cd .. && rm -rf ./emu2 )
    - ( cd /tmp && { git clone https://gitlab.com/johnsonjh/old_c.git || git clone https://github.com/johnsonjh/old_c.git; } )
    - mkdir -p public
    - mkdir -p public/dev86
    - bcc -Md -v -o crc.com crc.c && upx --8086 -9v crc.com && mv -vf crc.com public/dev86 && emu2 public/dev86/crc.com --auto public/dev86/crc.com crc.c
    - mkdir -p public/TC10
    - env EMU2_APPEND=/tmp/old_c/TCPP101/bin EMU2_DRIVE_C=/tmp/old_c/TCPP101 EMU2_DRIVE_D=. emu2 /tmp/old_c/TCPP101/bin/tcc.exe -Iinclude -Llib -G -O -Z -f- -mt -lt "D:\crc.c" -- PATH='C:\BIN' LIB='C:\LIB' INCLUDE='C:\INCLUDE' && cp -v /tmp/old_c/TCPP101/crc.com . && rm -vf /tmp/old_c/TCPP101/crc.* && upx --8086 -9v crc.com && mv -vf crc.com public/TC10 && emu2 public/TC10/crc.com --auto public/TC10/crc.com crc.c
    - mkdir -p public/TC15
    - env EMU2_APPEND=/tmp/old_c/TC15 EMU2_DRIVE_C=/tmp/old_c/TC15 EMU2_DRIVE_D=. emu2 /tmp/old_c/TC15/tcc.exe -I. -L. -G -O -Z -f- -mt "D:\crc.c" -- PATH='C:\' LIB='C:\' INCLUDE='C:\' && env EMU2_DOSVER=3.20 EMU2_DRIVE_C=/tmp/old_c/TC15 EMU2_DRIVE_D=. emu2 /tmp/old_c/TC15/exe2bin.exe crc.exe crc.com && cp -v /tmp/old_c/TC15/crc.com . && rm -vf /tmp/old_c/TC15/crc.* && upx --8086 -9v crc.com && mv -vf crc.com public/TC15 && emu2 public/TC15/crc.com --auto public/TC15/crc.com crc.c
    - mkdir -p public/TC10
    - env EMU2_APPEND=/tmp/old_c/TC10 EMU2_DRIVE_C=/tmp/old_c/TC10 EMU2_DRIVE_D=. emu2 /tmp/old_c/TC10/tcc.exe -I. -L. -G -O -Z -f- -mt "D:\crc.c" -- PATH='C:\' LIB='C:\' INCLUDE='C:\' && env EMU2_DOSVER=3.20 EMU2_DRIVE_C=/tmp/old_c/TC10 EMU2_DRIVE_D=. emu2 /tmp/old_c/TC10/exe2bin.exe crc.exe crc.com && cp -v /tmp/old_c/TC10/crc.com . && rm -vf /tmp/old_c/TC10/crc.* && upx --8086 -9v crc.com && mv -vf crc.com public/TC10 && emu2 public/TC10/crc.com --auto public/TC10/crc.com crc.c
    - mkdir -p public/MSC600A
    - ( cd /tmp/old_c/MSC600A ; cp -vf ~/crc/crc.c . && emu2 bin/cl.exe /W2 /AT /O /Ot /Ol /Og /Oi /Gr /Gs /Fecrc.com crc.c -- INCLUDE=include LIB=lib PATH='bin;binb' && upx --8086 -9v ~/public/MSC600A/crc.com && cp -vf crc.com ~/public/MSC600A && rm -vf crc.* )
  artifacts:
    expire_in: 1 day
    paths:
      - public
  retry: 2
  timeout: 60 minutes
  interruptible: false

###############################################################################
