###############################################################################
# .gitlab-ci.yml
# Copyright (c) 2026 Jeffrey H. Johnson
# SPDX-License-Identifier: MIT-0
# scspell-id: 03a06400-54ce-11f1-9a53-80ee73e9b8e7
###############################################################################

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 0

###############################################################################

before_script:
  - |
    # Start of Pre-setup ...
    echo -e "section_start:`date +%s`:Pre-setup_section[collapsed=true]\r\e[0K\033[0;36mPre-setup ...\033[0m" || true
  - apk update || true
  - apk add git
  - git fetch origin
  - git checkout -B "$CI_COMMIT_REF_NAME" "origin/$CI_COMMIT_REF_NAME"
  - |
    # End of Pre-setup ...
    echo -e "section_end:`date +%s`:Pre-setup_section\r\e[0K" || true

###############################################################################

pages:
  stage: deploy
  image: alpine:edge
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - |
      # Start of Setup ...
      echo -e "section_start:`date +%s`:Setup_section[collapsed=true]\r\e[0K\033[0;36mSetup ...\033[0m" || true
    - export TZ=UTC
    - apk update || true
    - apk add '!usr-merge-nag' 2> /dev/null || true
    - apk upgrade --prune || true
    - apk add bear cage clang clang-analyzer cppcheck ctags dev86 dos2unix dosbox-staging editorconfig-checker emacs file file-dev flawfinder gcc gtk+3.0 libc-dev libepoxy libinput libxkbcommon make mesa-dri-gallium mesa-egl mesa-gbm mesa-gl pango py3-codespell python3-dev reuse seatd shellcheck shfmt upx wayland-libs-egl xwayland
    - ln -s /usr/bin/ec /usr/bin/editorconfig-checker 2> /dev/null || true
    - ( set -x; cd /tmp && git clone https://github.com/dmsc/emu2.git && cd emu2 && make -j $(nproc) && make install && cd .. && rm -rf ./emu2 )
    - ( set -x; cd /tmp && { git clone https://gitlab.com/johnsonjh/old_c.git || git clone https://github.com/johnsonjh/old_c.git; } )
    - mkdir -p $HOME/.local/venvs
    - python3 -m venv $HOME/.local/venvs/vamos
    - $HOME/.local/venvs/vamos/bin/pip install --upgrade pip
    - $HOME/.local/venvs/vamos/bin/pip install --upgrade amitools[vamos]
    - mkdir -p $HOME/.local/bin
    - printf '%s\n' '#!/bin/sh' 'exec "$HOME/.local/venvs/vamos/bin/vamos" "$@"' > "$HOME/.local/bin/vamos"
    - chmod a+x "$HOME/.local/bin/vamos"
    - export PATH="$HOME/.local/bin:$PATH"
    - mkdir -p public
    - |
      # End of Setup ...
      echo -e "section_end:`date +%s`:Setup_section\r\e[0K" || true
    - |
      # Start of lint ...
      echo -e "section_start:`date +%s`:Lint_section[collapsed=true]\r\e[0K\033[0;36mmake lint ...\033[0m" || true
    - env OVERRIDE_PAUSE=1 make lint
    - |
      # End of lint ...
      echo -e "section_end:`date +%s`:Lint_section\r\e[0K" || true
    - |
      # Start of test ...
      echo -e "section_start:`date +%s`:Test_section[collapsed=true]\r\e[0K\033[0;36mmake test ...\033[0m" || true
    - make test
    - |
      # End of test ...
      echo -e "section_end:`date +%s`:Test_section\r\e[0K" || true
    - |
      # Start of dev86 build ...
      echo -e "section_start:`date +%s`:dev86_section[collapsed=true]\r\e[0K\033[0;36mdev86 build ...\033[0m" || true
    - mkdir -p public/dev86
    - ( set -x; ( bcc -v 2>&1 | head -1 || true ); bcc -Md -O -v -o crc.com crc.c && upx --8086 --best crc.com 2>&1 | grep '\->' && mv -f crc.com public/dev86 && emu2 public/dev86/crc.com --auto public/dev86/crc.com crc.c )
    - |
      # End of dev86 build ...
      echo -e "section_end:`date +%s`:dev86_section\r\e[0K" || true
    - |
      # Start of Turbo C++ 1.01 build ...
      echo -e "section_start:`date +%s`:TCPP101_section[collapsed=true]\r\e[0K\033[0;36mTurbo C++ 1.01 build ...\033[0m" || true
    - mkdir -p public/TCPP101
    - ( set -x; env EMU2_APPEND=/tmp/old_c/TCPP101/bin EMU2_DRIVE_C=/tmp/old_c/TCPP101 EMU2_DRIVE_D=. emu2 /tmp/old_c/TCPP101/bin/tcc.exe -Iinclude -Llib -G -O -Z -f- -mt -lt "D:\crc.c" -- PATH='C:\BIN' LIB='C:\LIB' INCLUDE='C:\INCLUDE' && cp -f /tmp/old_c/TCPP101/crc.com . && rm -f /tmp/old_c/TCPP101/crc.* && upx --8086 --best crc.com 2>&1 | grep '\->' && mv -f crc.com public/TCPP101 && emu2 public/TCPP101/crc.com --auto public/TCPP101/crc.com crc.c )
    - |
      # End of Turbo C++ 1.01 build ...
      echo -e "section_end:`date +%s`:TCPP101_section\r\e[0K" || true
    - |
      # Start of Turbo C 1.5 build ...
      echo -e "section_start:`date +%s`:TC15_section[collapsed=true]\r\e[0K\033[0;36mTurbo C 1.5 build ...\033[0m" || true
    - mkdir -p public/TC15
    - ( set -x; env EMU2_APPEND=/tmp/old_c/TC15 EMU2_DRIVE_C=/tmp/old_c/TC15 EMU2_DRIVE_D=. emu2 /tmp/old_c/TC15/tcc.exe -I. -L. -G -O -Z -f- -mt "D:\crc.c" -- PATH='C:\' LIB='C:\' INCLUDE='C:\' && env EMU2_DOSVER=3.20 EMU2_DRIVE_C=/tmp/old_c/TC15 EMU2_DRIVE_D=. emu2 /tmp/old_c/TC15/exe2bin.exe crc.exe crc.com && cp -f /tmp/old_c/TC15/crc.com . && rm -f /tmp/old_c/TC15/crc.* && upx --8086 --best crc.com 2>&1 | grep '\->' && mv -f crc.com public/TC15 && emu2 public/TC15/crc.com --auto public/TC15/crc.com crc.c )
    - |
      # End of Turbo C 1.5 build ...
      echo -e "section_end:`date +%s`:TC15_section\r\e[0K" || true
    - |
      # Start of Turbo C 1.0 build ...
      echo -e "section_start:`date +%s`:TC10_section[collapsed=true]\r\e[0K\033[0;36mTurbo C 1.0 build ...\033[0m" || true
    - mkdir -p public/TC10
    - ( set -x; env EMU2_APPEND=/tmp/old_c/TC10 EMU2_DRIVE_C=/tmp/old_c/TC10 EMU2_DRIVE_D=. emu2 /tmp/old_c/TC10/tcc.exe -I. -L. -G -O -Z -f- -mt "D:\crc.c" -- PATH='C:\' LIB='C:\' INCLUDE='C:\' && env EMU2_DOSVER=3.20 EMU2_DRIVE_C=/tmp/old_c/TC10 EMU2_DRIVE_D=. emu2 /tmp/old_c/TC10/exe2bin.exe crc.exe crc.com && cp -f /tmp/old_c/TC10/crc.com . && rm -f /tmp/old_c/TC10/crc.* && upx --8086 --best crc.com 2>&1 | grep '\->' && mv -f crc.com public/TC10 && emu2 public/TC10/crc.com --auto public/TC10/crc.com crc.c )
    - |
      # End of Turbo C 1.0 build ...
      echo -e "section_end:`date +%s`:TC10_section\r\e[0K" || true
    - |
      # Start of Microsoft C 6.00A build ...
      echo -e "section_start:`date +%s`:MSC600A_section[collapsed=true]\r\e[0K\033[0;36mMicrosoft C 6.00A build ...\033[0m" || true
    - mkdir -p public/MSC600A
    - true -- NOTE -- 'warning C4135 - conversion between different integral types' messages are expected for MSC600A builds!
    - ( set -x; cd /tmp/old_c/MSC600A && cp -f $CI_PROJECT_DIR/crc.c . && emu2 bin/cl.exe /W4 /AT /O /Ot /Ol /Og /Oi /Gr /Gs /Fecrc.com crc.c -- INCLUDE=include LIB=lib PATH='bin;binb' && upx --8086 --best crc.com 2>&1 | grep '\->' && cp -f crc.com $CI_PROJECT_DIR/public/MSC600A && emu2 $CI_PROJECT_DIR/public/MSC600A/crc.com --auto crc.com crc.c && rm -f crc.* )
    - |
      # End of Microsoft C 6.00A build ...
      echo -e "section_end:`date +%s`:MSC600A_section\r\e[0K" || true
    - |
      # Start of Aztec C68K/Amiga 5.2a build ...
      echo -e "section_start:`date +%s`:C68Amiga52a_section[collapsed=true]\r\e[0K\033[0;36mAztec C68K/Amiga 5.2a build ...\033[0m" || true
    - mkdir -p public/Aztec_C68K_Amiga_5.2a
    - ( set -x; export CCTEMP="/tmp" && export CLIB="$PWD/lib/libs" && export INCLUDE="$PWD/include:$PWD/asm" && VAMOS_FLAGS="-l mem_alloc:error,lib:error,main:error" && cd /tmp/old_c/Aztec_C68K_Amiga_5.2a && cp -f $CI_PROJECT_DIR/crc.c . && rm -f ./as && ln -f -s ./bin/as ./as && vamos $VAMOS_FLAGS -- ./bin/cc -sf -sn -sp -sr -ss -pa -pl -sa -sb -mc -md -Iinclude -o crc.r crc.c && rm -f ./as && vamos $VAMOS_FLAGS -- ./bin/ln -qv -t crc.r -T -O crc -llib/libs/c && cp -f crc $CI_PROJECT_DIR/public/Aztec_C68K_Amiga_5.2a && rm -f crc crc.* && cd $CI_PROJECT_DIR/public/Aztec_C68K_Amiga_5.2a && vamos $VAMOS_FLAGS -- ./crc --auto crc )
    - |
      # End of Aztec C68K/Amiga 5.2a build ...
      echo -e "section_end:`date +%s`:C68Amiga52a_section\r\e[0K" || true
    - |
      # Start of Microsoft C 8.00c build ...
      echo -e "section_start:`date +%s`:MSC800c_section[collapsed=true]\r\e[0K\033[0;36mMicrosoft C 8.00c build ...\033[0m" || true
    - mkdir -p public/MSC800c
    - mkdir -p /tmp/xdg && chmod 700 /tmp/xdg && export XDG_RUNTIME_DIR=/tmp/xdg
    - mkdir -p /root/.config/dosbox/
    - printf '%s\n' "[sdl]" "output = texture" "texture_renderer = software" "[render]" "glshader = none" "[mixer]" "nosound = true" > /root/.config/dosbox/dosbox-staging.conf
    - cd /tmp/old_c/MSC800c
    - cp -f ../UTILS/REDIR.COM .
    - export WLR_BACKENDS=headless
    - export GALLIUM_DRIVER=llvmpipe
    - export SEATD_SOCK=/run/seatd.sock
    - ( seatd -g root > /dev/null 2>&1 & ) && sleep 1
    - ( cage -s > /dev/null 2>&1 & ) && sleep 1
    - export WAYLAND_DISPLAY="$(ls $XDG_RUNTIME_DIR | grep -E '^wayland-[0-9]+$')"
    - rm -f build.bat OUT.TXT > /dev/null 2>&1 || true
    - cp -f $CI_PROJECT_DIR/crc.c .
    - cp -f $CI_PROJECT_DIR/suppress.h .
    - cat vars.bat > build.bat && printf '%s\n' "cl.exe /W4 /AT /O /Ot /Ol /Og /Oi /Oc /Oe /Gr /Gs /Ob2 /Oz /G0 /Fecrc.com crc.c" >> build.bat
    - unix2dos build.bat 2> /dev/null
    - env SDL_VIDEODRIVER=wayland dosbox . --exit -c "redir command.com /c build.bat > out.txt" -set "cpu core=dynamic" -set "cpu cycles=max" > /dev/null 2>&1
    - rm -f build.bat > /dev/null 2>&1 || true
    - cat OUT.TXT
    - rm -f OUT.TXT > /dev/null 2>&1 || true
    - test -f CRC.COM
    - mv -f CRC.COM crc.com && rm -f CRC.*
    - upx --8086 --best crc.com 2>&1 | grep '\->'
    - cp -f crc.com $CI_PROJECT_DIR/public/MSC800c
    - emu2 $CI_PROJECT_DIR/public/MSC800c/crc.com --auto crc.com crc.c
    - rm -f crc.*
    - cd
    - |
      # End of Microsoft C 8.00c build ...
      echo -e "section_end:`date +%s`:MSC800c_section\r\e[0K" || true
  artifacts:
    expire_in: 1 day
    paths:
      - public
  retry: 2
  timeout: 60 minutes
  interruptible: false

###############################################################################
